### ISSUE TITLE
Scaling instances of the daemon

### ISSUE THREAD

**Issue by sudoforge** [sudoforge/docker-mumble-server#6] opened 2016-10-07 19:36 UTC
What does scaling murmurd clients look like? How do multiple instances (with the same configuration) benefit the user?

The most straightforward "scaling" in the context of murmurd instances would be from `docker-compose scale`, and the firstmost benefit is enabling automatic failover for any user of this repository.

**Comment by bddenhartog** [comment] 2016-10-09 07:15
The basic idea behind this is to move this repository to `docker-compose`, and package a proxy with it to automatically serve the various murmurd processes (containers) automatically.

Maybe this should be done in another repository, and this repository left as simply the `docker-murmur` image. What do you think, @SISheogorath?

**Comment by SISheogorath** [comment] 2016-10-09 21:41
I think we can add compose file here too. There is no need to split this again. As we should update the compose file with every new release of a new mumble version it would be better to do this in a single repository.

I'm currently writing on a best practice guide about docker. There I point out that splitting docker file from Software projects is not the best solution. So yes, if my Dockerfile is maintained by the software project itself, than you would split out the compose file as long as it can run without. 

In our case the Dockerfile  is already split in a separated repository so we should not split again.

I'm currently working on `ice` support to the mumble image. So docker compose will be useful.

**Comment by bddenhartog** [comment] 2016-10-10 00:25
@SISheogorath okay, that's what I was leaning towards, too - refactoring this project to primarily compose, and keeping the Dockerfile itself inside some subdirectory.

Since murmur clients can't be linked together (that I know of; I haven't really played around with the daemon for quite some time), "scaling" here really means "providing failover" -- all we need to do is share the database, since the configuration is always going to be consistent with `docker-compose scale`. If we utilize [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) and [JrCs/docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion), we could enable users to run `docker-compose up -d` and instantly get a failover-ready instance of murmur up and running.

---

Something else that I would like to tackle is enabling daemon communication so that, for example, I could run this repo on a machine in San Francisco and a machine in Australia, and have the connections shared/grouped together. This wouldn't really benefit voice latency at all, but it would reduce an end user's time-to-server and outgoing communications.

**Comment by SISheogorath** [comment] 2016-10-10 01:39
Well, in case of "providing failover" I would ask the question: What does providing failover really mean. And how does it work?

In case of Mumble we have servers with a stateful server. Means the server itself holds session information only for itself. As far as I know/see this is not stored in database. So if you want to provide failover as you may know it from http sessions. You need to have stored this information in a very fast database like memcache or redis. Nothing of this happens in case of murmur.

So "providing HA" means hold a server on standby. I can confirm that restarting our current docker container is faster than the reconnect of mumble. So there is no benefit of providing a standy server somewhere.

Also linking murmur daemons is not possible. 

The documentation only mentions:
> A single Murmur daemon can also run multiple Murmur servers on different TCP/UDP ports. 

I just checked the source code to confirm it. There is no possible way to link daemons/instances like you may know from IRC. This leads us to the conclusion that it's not possible to scale murmur itself horizontal.

So you can only link channels over multiple instances by writing (yes, I couldn't find one) a bot which forwards all audio from one server to another. This will cause other errors like ACL and missing username options. So it's not a nice solution in any possible way.

I am unhappy with it but currently scaling out is not an option and a standby server is useless as a restart is faster than the reconnect.

**Comment by bddenhartog** [comment] 2016-10-10 18:57
Hm, good points all around. I hadn't tested the time-to-reconnect; does the user not experience any disconnection if we stop/restart the murmur service?

**Comment by SISheogorath** [comment] 2016-10-10 19:02
When I restart my murmur instance the user gets disconnected. The mumble client automatically reconnects to the murmur instance. Restart of murmur takes ~2seconds while reconnect takes 5.

So it's not a no downtime setup but you have to reconnect anyways to create a new session on the standby server.

**Comment by bddenhartog** [comment] 2016-10-11 19:44
Okay, so it sounds like horizontal scaling is impossible for now, and it sounds like vertical scaling doesn't really make a whole lot of sense.

So this task can be backlogged; as far as migrating to `docker-compose`, the benefit would come form automatically provisioning a proxy server (e.g. with `nginx`) for the murmur daemon as well as the web ui, which will be addressed in their own respective tasks.

See:

- #24 Automatically provision a proxy
- #23 Ice + WebUI integration

**Closed** 2021-01-26 04:39 UTC
Labels: type:discussion
